### ISSUE TITLE
Nested bind mounts broken on macOS arm64 since Docker Desktop 4.67.0

### ISSUE THREAD

**Issue by HilSny** [docker/for-mac#7868]
## Description

After upgrading from Docker Desktop 4.66.1 to 4.67.0, nested/overlapping bind mounts no longer work on macOS Apple Silicon. The child mount destination appears empty inside the container (showing the host's empty directory rather than the overlay), causing runtime errors. Downgrading to 4.66.1 resolves the issue immediately.

This affects all services in our monorepo that use this pattern (9+ services).

## Reproduction

Given this `docker-compose.yml`:

```yaml
services:
  my-api:
    build:
      context: ./my-api
      dockerfile: Dockerfile-dev
    command: yarn start
    volumes:
      - ./my-api/src:/my-api/src
      - ./_shared:/my-api/src/shared
```

Where `./_shared` is a directory containing files, and `./my-api/src/shared` is an empty directory on the host (intended to be overlaid by the `_shared` mount).

**Expected:** `/my-api/src/shared` inside the container contains the contents of `./_shared`.

**Actual:** `/my-api/src/shared` inside the container is empty — it shows the host's empty directory instead of the `_shared` overlay. This happens regardless of volume declaration order (parent-first or child-first).

```
Error: Cannot find module './shared/graphql/scalars/JSON'
Require stack:
- /my-api/src/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1421:15)
```

## Steps to reproduce

1. Create a directory `_shared/` with files in it
2. Create a directory `my-api/src/shared/` (empty)
3. Use the docker-compose config above with overlapping bind mounts
4. Run `docker compose up`
5. Observe that `src/shared` is empty inside the container

## Workaround

Downgrade to Docker Desktop 4.66.1.

## Environment

- **Docker Desktop:** 4.67.0 (222858)
- **Docker Engine:** 29.3.1
- **Docker Compose:** v5.1.1
- **macOS:** Apple Silicon (arm64)
- **File sharing:** VirtioFS

## Notes

- Works perfectly in Docker Desktop 4.66.1, broken in 4.67.0
- Volume declaration order (parent-first vs child-first) makes no difference
- 4.67.0 release notes mention a fix for "race condition between Rosetta binfmt registration and virtiofs device availability" on Apple Silicon — this may have changed mount ordering/timing
- `docker compose config` shows the correct mount configuration
- `docker inspect` shows the correct mount destinations
- The mounts appear correct in metadata but the filesystem inside the container does not reflect the child overlay

**Comment by timothycraig** [comment]
I'm experiencing a similar issue after 4.66.1 -> 4.67.0 upgrade.

```yaml
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - "8080:8080"
```

Container logs:

```
client-1        | > vite
client-1        |
client-1        | sh: 1: vite: not found
```

Reverting to 4.66.1 fixed the issue.

**Comment by todeveni** [comment]
Same problem here with 4.67.0 (Apple Silicon and Intel). Downgrading to 4.66.1 fixed.
Why was this issue closed?

**Comment by HilSny** [comment]
I closed this issue because I accidentally created it without filling out the issue form properly. I created a new issue that you can follow here: https://github.com/docker/desktop-feedback/issues/264
