### ISSUE TITLE
Docker Desktop 4.25.0 Not Installing On macOS Big Sur 11.7.10

### ISSUE THREAD

**Issue by conradwt** [docker/for-mac#7071]
### Description

Docker Desktop 4.25.0 Not Installing On macOS Big Sur 11.7.10.  Thus, I'm getting the following message when I attempt to execute it via the icon:

You have macOS 11.7.10. The application requires macOS 12.0 or later.

### Reproduce

1. update an existing version of Docker Desktop For Mac

or 

2. download Docker Desktop for Mac 4.25.0

### Expected behavior

I expected that the latest Docker Desktop would install and work with fail.

### docker version

```bash
➜ docker version                                           
Cannot connect to the Docker daemon at unix:///Users/conradwt/.docker/run/docker.sock. Is the docker daemon running?
Client:
 Cloud integration: v1.0.35+desktop.5
 Version:           24.0.6
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        ed223bc
 Built:             Mon Sep  4 12:28:49 2023
 OS/Arch:           darwin/amd64
 Context:           desktop-linux
```

### docker info

```bash
➜ docker info   
Client:
 Version:    24.0.6
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2-desktop.5
    Path:     /Users/conradwt/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.23.0-desktop.1
    Path:     /Users/conradwt/.docker/cli-plugins/docker-compose
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/conradwt/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.20
    Path:     /Users/conradwt/.docker/cli-plugins/docker-extension
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.9
    Path:     /Users/conradwt/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/conradwt/.docker/cli-plugins/docker-sbom
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     /Users/conradwt/.docker/cli-plugins/docker-scan
  scout: Docker Scout (Docker Inc.)
    Version:  v1.0.9
    Path:     /Users/conradwt/.docker/cli-plugins/docker-scout

Server:
ERROR: Cannot connect to the Docker daemon at unix:///Users/conradwt/.docker/run/docker.sock. Is the docker daemon running?
errors pretty printing info
```

### Diagnostics ID

/Applications/Docker.app/Contents/MacOS/com.docker.diagnose dyld: Symbol not found: _OBJC_CLASS_$_VZSharedDirectory   Referenced from: /Applications/Docker.app/Contents/MacOS/com.docker.diagnose (which was built for Mac OS X 12.0)   Expected in: /System/Library/Frameworks/Virtualization.framework/Versions/A/Virtualization  in /Applications/Docker.app/Contents/MacOS/com.docker.diagnose

### Additional Info

There needs to be some compatibility matrix somewhere because I was updating an existing installed version.

**Comment by omarsafwany** [comment]
I am facing the same issue. I even tried re-downloading `v.4.24` but I get an error stating os version is not supported.

**Comment by gvzq** [comment]
@conradwt and @omarsafwany 

This ended up working for me:
- 4.24.0 (122432) at [Mac with Intel chip](https://desktop.docker.com/mac/main/amd64/122432/Docker.dmg?_gl=1*1djsy22*_ga*MjAyNzUwMzM5NC4xNjk5ODM5MTIx*_ga_XJWPQMJYHQ*MTY5OTgzOTEyMC4xLjEuMTY5OTg0MTcyNC41Ny4wLjA.) from https://docs.docker.com/desktop/release-notes/#4240.

It works but it will ask to update to the latest version. I hope it help you all!

![2023-11-12](https://github.com/docker/for-mac/assets/9647119/d14a3405-9464-411b-a2f0-02d925f6ec08)

**Comment by conradwt** [comment]
@gvzq Great, this worked, and thanks for the information.

**Comment by conradwt** [comment]
In general, the Docker team needs to clearly document macOS versions and associated Docker Desktop versions. Docker Desktop 4.25.0, a minor version, should work with macOS 11.7.10 (Big Sur).  Otherwise, it would have been better bump Docker Desktop to 5.0.0, document macOS requirements, and update the app's internal and external downloader to download the latest version that's compatible with the current version of the user's macOS version.

**Comment by omarsafwany** [comment]
@gvzq Didn't work at first so I went with the following [answer](https://stackoverflow.com/a/71861493/999885) which explained killing any docker related process using the Activity Monitor. It went a further step by clearing all containers, some mentioned it worked without this step, and then I reinstalled `v4.20` and it worked.

I then downloaded `v4.24` and it is working as well so I guess maybe `v4.25` is a bit breaking and was not compatible with macOS Big Sur 11.7.10.

Again thanks for your suggestion.

**Comment by stephen-turner** [comment]
Per the [system requirements](https://docs.docker.com/desktop/install/mac-install/), "Docker supports Docker Desktop on the most recent versions of macOS. That is, the current release of macOS and the previous two releases. As new major versions of macOS are made generally available, Docker stops supporting the oldest version and supports the newest version of macOS (in addition to the previous two releases)."

That's been our policy for years, but we do usually call it out in the release notes when a macOS version goes out of support, and I think we missed it this time. Sorry about that: we'll fix it.

PS Docker Desktop does not use semver.

**Comment by conradwt** [comment]
> Thanks for the report. Per the [system requirements](https://docs.docker.com/desktop/install/mac-install/), "Docker supports Docker Desktop on the most recent versions of macOS. That is, the current release of macOS and the previous two releases. As new major versions of macOS are made generally available, Docker stops supporting the oldest version and supports the newest version of macOS (in addition to the previous two releases)."
> 

This is vague at best as to what exact versions are supported by a Docker Desktop for Mac release.  Here's a better system requirements statement:

Docker Desktop 4.25.0 supports macOS 12 or newer.

or

Docker Desktop 4.25.0 supports the following macOS versions:

- macOS 12 (Monterey)
- macOS 13 (Ventura)
- macOS 14 (Sonoma)

Next, if Docker Desktop 4.25.0 doesn't support macOS 11 (Big Sur), then Docker Desktop 4.24.0 shouldn't be displaying the following page:

<img width="1382" alt="Screen Shot 2023-11-14 at 1 25 09 PM" src="https://github.com/docker/for-mac/assets/20219/14b25218-1229-41d7-8eb7-558847914092">

In general, the Docker team needs to update the downloader or its functionality to download the latest version that's compatible with the current version of the user's macOS version.  Otherwise, a user like myself will try to update to a version of Docker Desktop that's not compatible with their version of macOS.

> That's been our policy for years, but we do usually call it out in the release notes when a macOS version goes out of support, and I think we missed it this time. Sorry about that: we'll fix it.
> 
> PS Docker Desktop does not use semver.

**Comment by stephen-turner** [comment]
You're right, the update dialog is not supposed to appear if your OS isn't compatible with the new version. We will fix that too. And we will make the documentation more explicit.

**Comment by Nicnomadi** [comment]
**solution of gvzq here above worked !**
using Big Sur within VSCode  using the docker 4.24.0 (122432) at [Mac with Intel chip]

(https://desktop.docker.com/mac/main/amd64/122432/Docker.dmg?_gl=1*1djsy22*_ga*MjAyNzUwMzM5NC4xNjk5ODM5MTIx*_ga_XJWPQMJYHQ*MTY5OTgzOTEyMC4xLjEuMTY5OTg0MTcyNC41Ny4wLjA.) from https://docs.docker.com/desktop/release-notes/#4240.

working with VSCode I wanted to use docker on my intelchip Macbookpro 2016, I needed  minimal to upgrade from MacOs 11.7.10 to Macos 12 Monterey. should install but it does not.
I can not get Monterey working so i took a lower docker 4.24.0

Thank You

**Comment by aydinserbest** [comment]
my macbook is version 11.7.10 -big sur and i tried to install the docker  4.24.0 as described above, but after installing, it seems as version 4.23.0 
![Screenshot 2023-12-17 at 09 53 20](https://github.com/docker/for-mac/assets/101752975/a1f3ee38-7ef6-4a45-a367-3f60cf92ab7d)

![Screenshot 2023-12-17 at 09 49 57](https://github.com/docker/for-mac/assets/101752975/87df85d3-646c-47cb-b6ad-ea7caa7573c8)
and it doesn't work,

**Comment by aydinserbest** [comment]
@ #

> my macbook is version 11.7.10 -big sur and i tried to install the docker 4.24.0 as described above, but after installing, it seems as version 4.23.0 ![Screenshot 2023-12-17 at 09 53 20](https://private-user-images.githubusercontent.com/101752975/291051599-a1f3ee38-7ef6-4a45-a367-3f60cf92ab7d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4MDQzOTIsIm5iZiI6MTcwMjgwNDA5MiwicGF0aCI6Ii8xMDE3NTI5NzUvMjkxMDUxNTk5LWExZjNlZTM4LTdlZjYtNGE0NS1hMzY3LTNmNjBjZjkyYWI3ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxN1QwOTA4MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MDk5NTkyMTkxYmFkOTI3NDk2ZTk4OGY1YmJmY2YxNTkwN2EyMWIxY2E4YmYzZDg0ZDE3ZmU2NWUyOGFhMDFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cvQS0Od6b9s-j92F2J-Lq-wjPY2RbmXa7kgOjYJb2LI)
> 
> ![Screenshot 2023-12-17 at 09 49 57](https://private-user-images.githubusercontent.com/101752975/291051556-87df85d3-646c-47cb-b6ad-ea7caa7573c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4MDQzOTIsIm5iZiI6MTcwMjgwNDA5MiwicGF0aCI6Ii8xMDE3NTI5NzUvMjkxMDUxNTU2LTg3ZGY4NWQzLTY0NmMtNDdjYi1iNmFkLWVhN2NhYTc1NzNjOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxN1QwOTA4MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZmNlZTNhZmNmZmY5NmRkMzA2ZWNiMmM3M2QzNGZhY2M5NTMwN2I4YzY3ZDNhNzI4ZjkyNzMyNzA5YWFmYWI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ETMyUv9Pu6Hw_mQ95S9Md72-VCizNKSi1SX2wyITTp4) and it doesn't work,

i rebooted the macbook and tried again to install, now it works. Thanks
![Screenshot 2023-12-17 at 10 12 32](https://github.com/docker/for-mac/assets/101752975/d2641a94-2314-4758-8b6b-eaea0f292ce4)

**Comment by asifaftab87** [comment]
> @conradwt and @omarsafwany
> 
> This ended up working for me:
> 
> * 4.24.0 (122432) at [Mac with Intel chip](https://desktop.docker.com/mac/main/amd64/122432/Docker.dmg?_gl=1*1djsy22*_ga*MjAyNzUwMzM5NC4xNjk5ODM5MTIx*_ga_XJWPQMJYHQ*MTY5OTgzOTEyMC4xLjEuMTY5OTg0MTcyNC41Ny4wLjA.) from https://docs.docker.com/desktop/release-notes/#4240.
> 
> It works but it will ask to update to the latest version. I hope it help you all!
> 
> ![2023-11-12](https://private-user-images.githubusercontent.com/9647119/282347071-d14a3405-9464-411b-a2f0-02d925f6ec08.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxODkwODUsIm5iZiI6MTcwODE4ODc4NSwicGF0aCI6Ii85NjQ3MTE5LzI4MjM0NzA3MS1kMTRhMzQwNS05NDY0LTQxMWItYTJmMC0wMmQ5MjVmNmVjMDguanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTdUMTY1MzA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODNkNmQxY2RmZTM4ODgwYzRkZTk1ZDg1MGI4NGNlZDU3ODE2NzI2NDM2ZDk3YTliYTZkNmZlMDU5MWUzYjEzNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ryx0fqrURuqbTFyiTo0Mwkt7j-AlJ4ASVOkzc6Eu-aI)

great
works for me
thank you so much

**Comment by ola-lekan01** [comment]
Version 4.24.0 Worked for me as well.

Thanks

> @conradwt and @omarsafwany
> 
> This ended up working for me:
> 
>     * 4.24.0 (122432) at [Mac with Intel chip](https://desktop.docker.com/mac/main/amd64/122432/Docker.dmg?_gl=1*1djsy22*_ga*MjAyNzUwMzM5NC4xNjk5ODM5MTIx*_ga_XJWPQMJYHQ*MTY5OTgzOTEyMC4xLjEuMTY5OTg0MTcyNC41Ny4wLjA.) from https://docs.docker.com/desktop/release-notes/#4240.
> 
> 
> It works but it will ask to update to the latest version. I hope it help you all!
> 
> ![2023-11-12](https://private-user-images.githubusercontent.com/9647119/282347071-d14a3405-9464-411b-a2f0-02d925f6ec08.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3NDgyMzcsIm5iZiI6MTcxMTc0NzkzNywicGF0aCI6Ii85NjQ3MTE5LzI4MjM0NzA3MS1kMTRhMzQwNS05NDY0LTQxMWItYTJmMC0wMmQ5MjVmNmVjMDguanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjlUMjEzMjE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjFkM2FkYzkwOGM5NmNmYTg0ODIzN2NkYmJlYjhjMzc2ZmY2NjAxODJlZDU1N2M1MWVmNzJhZGU0YWYzZGUyNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.9fC7u8T_LBHPqx3UoL1cvvgISj0DQQqUVJoNmep_uT0)



Version 4.24.0 Worked for me as well.

Thanks

**Comment by missedmyeye** [comment]
> This ended up working for me:
> 
> * 4.24.0 (122432) at [Mac with Intel chip](https://desktop.docker.com/mac/main/amd64/122432/Docker.dmg?_gl=1*1djsy22*_ga*MjAyNzUwMzM5NC4xNjk5ODM5MTIx*_ga_XJWPQMJYHQ*MTY5OTgzOTEyMC4xLjEuMTY5OTg0MTcyNC41Ny4wLjA.) from https://docs.docker.com/desktop/release-notes/#4240.

I'm in the midst of trying to make some use out of an old laptop so this was super helpful. still works!
(Macbook Pro with Intel Chip, Big Sur 11.7.10)

**Comment by TimElector** [comment]
Did not work for me first, but after a reboot it did.
