### ISSUE TITLE
docker-compose AttributeError: 'NoneType' object has not attribute 'get'

### ISSUE THREAD

**Issue by gottfrois** [docker/for-mac#912]
### Expected behavior

Launching my service using docker-compose:

```
$ docker-compose up mongo
```

### Actual behavior

```
$ docker-compose up mongo
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose/cli/main.py", line 65, in main
  File "compose/cli/main.py", line 114, in perform_command
  File "compose/cli/command.py", line 36, in project_from_options
  File "compose/cli/command.py", line 103, in get_project
  File "compose/config/config.py", line 323, in load
  File "compose/config/config.py", line 414, in load_services
  File "compose/config/config.py", line 405, in merge_services
  File "compose/config/config.py", line 405, in <dictcomp>
  File "compose/config/config.py", line 704, in merge_service_dicts_from_files
  File "compose/config/config.py", line 774, in merge_service_dicts
  File "compose/config/config.py", line 728, in merge_field
  File "compose/config/config.py", line 807, in merge_logging
  File "compose/config/config.py", line 750, in merge_scalar
AttributeError: 'NoneType' object has no attribute 'get'
docker-compose returned -1
```

### Information

Does not seems to be related to mongo image in particular since it does not work with `redis` as well.
Worked well on previous docker version (beta29.2)

Diagnostic ID: `DC0A292B-2A42-41FB-8C7A-189D69ACE994`

### Steps to reproduce the behavior

docker-compose.yml:

```
version: '2'

services:
  mongo:
    container_name: mongo
    image: mongo:3.2
    command: ["--storageEngine", "wiredTiger"]
    ports:
      - "27017"
    volumes:
      - ./config/mongodb/mongodb-entrypoint.sh:/entrypoint.sh
      - ./db/mongo:/data/db
    logging:
      driver: json-file
      options:
        max-size: '10k'
        max-file: '3'
```

**Comment by dsheets** [comment]
Hello! I think this may be a duplicate of docker/compose#4103 which will arrive in a beta soon. If you don't believe this is the same issue, please feel free to reopen. Thanks for your report!
